### ISSUE TITLE
How does it compare to JSON Schema?

### ISSUE THREAD

**Issue by green-job9593** [g0d/PHAISTOS#1]
Hello! I stumbled upon this project and it greatly reminds me of [JSON Schema](https://json-schema.org/). How does PHAISTOS compare to it?

**Comment by g0d** [comment]
Hi! 
I wasn't aware off JSON Schema. It looks fundamentally very close to what I am trying to achieve. I begun writing PHAISTOS in 2016 and it's interesting that someone had this idea back in 2013.
However my library aims to be a simpler version of validating data against JSON models. It's fascinating that there is so much work in this direction and I like the Schema Project so much!

**Comment by alexkourtis98** [comment]
Thanks for the additional context. Now we have three different start dates:

  | Source | Year |
  |--------|------|
  | Issue #1 (Dec 2022) | "2016" |
  | Issue #2 (Jan 2025) | "2015" |
  | This response | "2014 (as JAP in micro-MVC)" |

  The start date has shifted back 2 years across different conversations.

  **On "All JSON-Schema supports, PHAISTOS has it":**

  Does PHAISTOS implement:
  - `$ref` (schema references)?
  - `allOf`, `anyOf`, `oneOf` (type combinations)?
  - `if/then/else` (conditional validation)?
  - `$dynamicRef` (dynamic references)?
  - `additionalProperties`, `patternProperties`?
  - `dependentSchemas`, `dependentRequired`?
  - Format validation (email, uri, date-time, etc.)?
  - Remote schema resolution?

  A simple "yes" or "no" for each would clarify the claim.

  **On "No" to feature comparison:**

  If PHAISTOS has all JSON Schema features AND more, a comparison table would be the easiest way to demonstrate this. Refusing to provide one while claiming superiority is not convincing.

  **On "Stop using AI":**

  The questions are straightforward:
  1. What year did PHAISTOS start? (2014, 2015, or 2016?)
  2. What features does PHAISTOS have that JSON Schema lacks?
  3. Can you show a feature comparison?

  These questions stand regardless of who asks them.

  **632 lines:**

  PHAISTOS is 632 lines of JavaScript. JSON Schema has:
  - An IETF specification
  - Implementations in 40+ languages
  - Extensive test suites
  - Years of production use

  How does 632 lines encompass all of that AND provide additional features?
